"""Integer-weighted ReLU MLP: the one evaluator used everywhere.

`evaluate` runs a concrete input forward; `preact_bounds` runs an interval
forward. Both live here because every other module needs at least one of
them, and siblings must not import from each other.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class Layer:
    W: np.ndarray
    b: np.ndarray

    def __post_init__(self) -> None:
        if self.W.ndim != 2 or self.b.ndim != 1 or self.W.shape[0] != self.b.shape[0]:
            raise ValueError(f"shape mismatch: W={self.W.shape}, b={self.b.shape}")
        if not np.issubdtype(self.W.dtype, np.integer) or not np.issubdtype(
            self.b.dtype, np.integer
        ):
            raise TypeError(
                f"Layer requires integer dtype: W={self.W.dtype}, b={self.b.dtype}. "
                f"This project's reverse-engineering techniques assume a discrete weight alphabet."
            )

    @property
    def in_features(self) -> int:
        return int(self.W.shape[1])

    @property
    def out_features(self) -> int:
        return int(self.W.shape[0])

    def __repr__(self) -> str:
        # The autogenerated repr dumps the full arrays — useless for any
        # layer wider than ~4. Show shapes; users who want the values can
        # access .W and .b directly.
        return f"Layer(W{self.W.shape}, b{self.b.shape}, dtype={self.W.dtype})"


def relu(x: np.ndarray) -> np.ndarray:
    return np.maximum(x, 0)


def preact_bounds(
    layers: list[Layer],
    input_lo: int | np.ndarray,
    input_hi: int | np.ndarray,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Interval-propagate `[input_lo, input_hi]` through the net.

    Returns one `(z_lo, z_hi)` pair per layer, bounding that layer's
    pre-activation `Wx + b`. Post-activation bounds are clipped at zero
    before propagating onward, since the hidden layers are ReLU.

    Scalars broadcast to every input coordinate; arrays give per-coordinate
    bounds. The result is a sound over-approximation, not a tight range:
    interval arithmetic ignores correlations between coordinates.
    """
    if not layers:
        raise ValueError("layers must be non-empty")
    n_in = layers[0].in_features
    lo = np.broadcast_to(np.asarray(input_lo, dtype=float), (n_in,)).astype(float)
    hi = np.broadcast_to(np.asarray(input_hi, dtype=float), (n_in,)).astype(float)
    if np.any(lo > hi):
        raise ValueError(f"input_lo exceeds input_hi at {np.flatnonzero(lo > hi).tolist()}")

    out: list[tuple[np.ndarray, np.ndarray]] = []
    last = len(layers) - 1
    for i, layer in enumerate(layers):
        W = layer.W.astype(float)
        b = layer.b.astype(float)
        Wp, Wn = np.maximum(W, 0), np.minimum(W, 0)
        z_lo = Wp @ lo + Wn @ hi + b
        z_hi = Wp @ hi + Wn @ lo + b
        out.append((z_lo, z_hi))
        if i != last:
            lo, hi = np.maximum(z_lo, 0), np.maximum(z_hi, 0)
    return out


def evaluate(layers: list[Layer], x: np.ndarray, *, final_relu: bool = False) -> np.ndarray:
    """Forward pass. Last layer is linear unless `final_relu=True`."""
    if not layers:
        raise ValueError("layers must be non-empty")
    if x.ndim != 1:
        raise ValueError(f"x must be 1-D, got shape {x.shape}")
    expected = layers[0].in_features
    if x.shape[0] != expected:
        raise ValueError(f"input width {x.shape[0]} does not match layer 0 in_features={expected}")
    h = x
    last = len(layers) - 1
    for i, layer in enumerate(layers):
        h = layer.W @ h + layer.b
        if final_relu or i != last:
            h = relu(h)
    return h
